In [17]:
import pandas as pd 
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [18]:
# load the dataset
data = pd.read_csv("Churn_Modelling.csv")

In [19]:


data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [20]:
data.shape


(10000, 14)

In [22]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [23]:
# preprocessing the data  
# drop irrelevant columns(rowno , customerid , surname)

data=data.drop(['RowNumber','CustomerId','Surname'],axis=1) 

In [24]:
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64  
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB


In [ ]:
data.isnull().any()    # no missing values 

CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [ ]:
# we have 2 categorical column ; we have to just encode it  

label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])  # applied label encoding

In [28]:
data.head()


CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [29]:
# now we have to encode the country column using one hot encoding 
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder() 
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])  # applied one hot encoding


In [32]:
print(geo_encoder.toarray())  # to see the one hot encoded values

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [33]:
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [ ]:
onehot_encoder_geo.get_feature_names_out(['Geography'])  # to get the names of the one hot encoded columns

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

now i have to convert this oh encoded data into data frame and have to attach with dataset

In [38]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))  # to convert the one hot encoded data into dataframe

In [39]:
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [40]:
#lets concatenate the geo_encoded_df with original dataset
data = pd.concat([data, geo_encoded_df], axis=1)

In [42]:
data =  data.drop(['Geography'], axis=1)  # drop the original Geography column as we have already encoded it

In [43]:
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

In [45]:
## saving the preprocessed data into a pickle file
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [47]:
# exited is output feature 
X = data.drop(['Exited'], axis=1)  # input features - take all the colum except 'Exited'
Y = data['Exited']

In [48]:
#now splitting the data into train test split 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# scaling the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)  # fit and transform the training data
X_test = scaler.transform(X_test)  # transform the test data using the same scaler

In [49]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [50]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [51]:
## saving the preprocessed data into a pickle file
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler,file)


In [52]:
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

## ANN Implementation

In [53]:

import tensorflow as tf
from tensorflow import keras 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [55]:
# lets build the ANN model -> create a sequential model . 
model = Sequential([
Dense(64, activation='relu', input_shape=(X_train.shape[1],)),  # first hidden layer with 64 neurons and relu activation conneted with input layer 
Dense(32, activation='relu'),  # second hidden layer with 32 neurons and relu activation
Dense(1, activation='sigmoid'),  #output layer with 16 neurons and rel
])  

In [56]:
model.summary()  # to see the summary of the model

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 64)                832       
                                                                 
 dense_2 (Dense)             (None, 32)                2080      
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [62]:
# loading optimizer 
import tensorflow 
opt= tensorflow.keras.optimizers.Adam(learning_rate=0.01) # using Adam optimizer with learning rate of 0.001

In [64]:
## compile the model 
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])  # compile the model with optimizer , loss function and metrics

In [65]:
## set up the tensorboard for visuALIZATION 
from tensorflow.keras.callbacks import TensorBoard,EarlyStopping
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")  # create a log directory with current timestamp
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)  # create a tensorboard callback

In [67]:
## set up early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)  # early stopping callback to prevent overfitting # how it workss-> if the validation loss does not improve for 5 epochs, it will stop training and restore the best weights

In [68]:
#taining the model 
history = model.fit(
    X_train, Y_train, epochs=100, batch_size=32, validation_data= (X_test, Y_test), callbacks=[tensorboard_callback, early_stopping_callback])  # fit the model with training data and validation split

Epoch 1/100


250/250 [==============================] - 2s 4ms/step - loss: 0.4001 - accuracy: 0.8339 - val_loss: 0.3484 - val_accuracy: 0.8630
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3569 - accuracy: 0.8521 - val_loss: 0.3602 - val_accuracy: 0.8580
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3479 - accuracy: 0.8543 - val_loss: 0.3443 - val_accuracy: 0.8605
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3435 - accuracy: 0.8599 - val_loss: 0.3400 - val_accuracy: 0.8595
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3405 - accuracy: 0.8549 - val_loss: 0.3590 - val_accuracy: 0.8570
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3364 - accuracy: 0.8625 - val_loss: 0.3420 - val_accuracy: 0.8605
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3374 - accuracy: 0.8633 - val_loss: 0.3390 - val_accuracy: 0.86

In [70]:
model.save('model.h5')

c:\Users\91774\OneDrive\Desktop\AI_ML Peojects\venv_deeplearning\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [71]:
## load the tensorboard Extension 
%load_ext tensorboard

In [72]:
%tensorboard --logdir logs/fit  # to start the tensorboard server and visualize the training process

In [ ]:
##